global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'vidalstephen@gmail.com'
  smtp_auth_username: 'vidalstephen@gmail.com'
  smtp_auth_password: 'fumnhtabgaffbfhp'  # Gmail App Password!
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  receiver: 'default-email'

  routes:
    - match:
        severity: 'critical'
      receiver: 'critical-email-telegram'
      continue: false

    - match:
        severity: 'warning'
      receiver: 'warning-email'
      continue: false

    - match:
        severity: 'info'
      receiver: 'info-telegram'
      continue: false

receivers:
  - name: 'default-email'
    email_configs:
      - to: 'vidalstephen@gmail.com'
        send_resolved: true

  - name: 'critical-email-telegram'
    email_configs:
      - to: 'vidalstephen@gmail.com'
        send_resolved: true
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: '7803452046:AAE1V5nXY-tWRTTQyTjRCaqx7lwusyuNUuA'
        chat_id: 6548187385
        message: '{{ template "telegram.default" . }}'
        parse_mode: 'HTML'
        send_resolved: true

  - name: 'warning-email'
    email_configs:
      - to: 'vidalstephen@gmail.com'
        send_resolved: true

  - name: 'info-telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: '7803452046:AAE1V5nXY-tWRTTQyTjRCaqx7lwusyuNUuA'
        chat_id: 6548187385
        message: '{{ template "telegram.default" . }}'
        parse_mode: 'HTML'
        send_resolved: true

# Optionally, you can customize the telegram message template:
templates:
  - '/etc/alertmanager/telegram.tmpl'
