global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'karaoke-status-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['status-api:5001']
